### ISSUE TITLE
Install fail on Magento 2.3.4 Enterprise

### ISSUE THREAD

**Issue by daaru00** [dotmailer/dotmailer-magento2-extension-enterprise#19]
Hello,

I incur in an error during a clean installation of Magento 2.3.4 enterprise, on `setup:upgrade`
```
In Processor.php line 92:
                                                                               
  [Magento\Framework\Exception\InputException]                                 
  Constraint "email_order_to_sales_order" references table that does not exist.
```
seems related to this: https://github.com/dotmailer/dotmailer-magento2-extension-enterprise/blob/master/etc/constraints.xml#L4

Checking in Magento database that table does not exist:
```
select * from email_order_to_sales_order
```
```
Error Code: 1146. Table 'magento.email_order_to_sales_order' doesn't exist
```

**Comment by sta1r** [comment]
Hello @daaru00 I'm sorry for the really long delay here. 

`email_order_to_sales_order` is the name of a constraint, not a table. That constraint references the core table `sales_order`, which may be missing in your case. 

Do come back to me if you need more help, but I'll assume your issue was resolved one way or another.
